// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Конфігурація для Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrgA4_2hKGN8ARhemZbDh7ST2HQ0nB-ik',
    appId: '1:159098473807:web:dc80ce12c7b3e6e9ed493a',
    messagingSenderId: '159098473807',
    projectId: 'min-blog-72d61',
    authDomain: 'min-blog-72d61.firebaseapp.com',
    storageBucket: 'min-blog-72d61.firebasestorage.app',
    measurementId: 'G-5ZY3X0S82V',
  );

  // Конфігурація для Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB0XJND6WId2fJKRLRSpr6LqsbzNLhuBk',
    appId: '1:159098473807:android:768b7ab76402099aed493a',
    messagingSenderId: '159098473807',
    projectId: 'min-blog-72d61',
    storageBucket: 'min-blog-72d61.firebasestorage.app',
  );

  // Конфігурація для iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6eIV7Yo-wl5pnWlggwAuB-tM6o-0iF-k',
    appId: '1:159098473807:ios:79ea31fd26d8826fed493a',
    messagingSenderId: '159098473807',
    projectId: 'min-blog-72d61',
    storageBucket: 'min-blog-72d61.firebasestorage.app',
    iosBundleId: 'com.example.minBlog19',
  );

  // Конфігурація для macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6eIV7Yo-wl5pnWlggwAuB-tM6o-0iF-k',
    appId: '1:159098473807:ios:79ea31fd26d8826fed493a',
    messagingSenderId: '159098473807',
    projectId: 'min-blog-72d61',
    storageBucket: 'min-blog-72d61.firebasestorage.app',
    iosBundleId: 'com.example.minBlog19',
  );

  // Конфігурація для Windows (ОНОВЛЕНО на основі вашого JS-конфігу)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCrgA4_2hKGN8ARhemZbDh7ST2HQ0nB-ik",
    appId: "1:159098473807:web:ff46aeeafd9c9496ed493a", // Примітка: windows часто має унікальний appId
    messagingSenderId: "159098473807",
    projectId: "min-blog-72d61",
    authDomain: "min-blog-72d61.firebaseapp.com",
    storageBucket: "min-blog-72d61.firebasestorage.app",
    // measurementId: "G-2EVZL5PX6D", // Необов'язково для Windows, але додаємо, якщо потрібно
  );
}